export const colors = {
  blue: "#407BFF",
  lightGray: "#F5F5F5",
  white: "#fff",
  black: "#000",
  mediumGray: "#888",
  darkGray: "#444",
  red: "#9B111E",
};

export const slides = [
  {
    id: 1,
    image: require("../../assets/Onboard1.png"),
    title: "Best Ecommerce Platform",
    subtitle: "Digitalize yourself for better daily life workouts",
  },
  {
    id: 2,
    image: require("../../assets/Onboard2.png"),
    title: "Easy For Your Use",
    subtitle: "We can ease your work with comfortable payment methods",
  },
  {
    id: 3,
    image: require("../../assets/Onboard3.png"),
    title: "Fast and Trustable",
    subtitle: "Enjoy with our best delivering policies",
  },
];
export const sliderImage = [
  require("../../assets/slide1.jpeg"),
  require("../../assets/slide2.jpeg"),
  require("../../assets/slide3.jpeg"),
  require("../../assets/slide4.jpeg"),
  require("../../assets/slide5.jpeg"),
];

export const imageSlider = [
  {
    id: 1,
    image: require("../../assets/slide1.jpeg"),
  },
  {
    id: 2,
    image: require("../../assets/slide2.jpeg"),
  },
  {
    id: 3,
    image: require("../../assets/slide3.jpeg"),
  },
  {
    id: 4,
    image: require("../../assets/slide4.jpeg"),
  },
  {
    id: 5,
    image: require("../../assets/slide5.jpeg"),
  },
];

export const clothesItem = [
  {
    id: 1,
    image: require("../../assets/tshirt.png"),
    title: "T-shirt",
    data: [
      {
        id: 1,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 2,
        name: "Custom Name Signature T-Shirt",
        image: require("../../assets/custom_name.jpg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 3,
        name: "Unisex White T-shirt",
        image: require("../../assets/white_tshirt.jpeg"),
        brand: "FullAddict",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 4,
        name: "V-Neck T-shirt",
        image: require("../../assets/V-neck.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 5,
        name: "Slim-Fit T-shirt",
        image: require("../../assets/slim_fit.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 6,
        name: "Ladies T-shirt",
        image: require("../../assets/ladies_shirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 7,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
    ],
  },
  {
    id: 2,
    image: require("../../assets/pant.png"),
    title: "Pants",
    data: [
      {
        id: 1,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 2,
        name: "Custom Name Signature T-Shirt",
        image: require("../../assets/custom_name.jpg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 3,
        name: "Unisex White T-shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "FullAddict",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 4,
        name: "V-Neck T-shirt",
        image: require("../../assets/V-neck.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 5,
        name: "Slim-Fit T-shirt",
        image: require("../../assets/slim_fit.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 6,
        name: "Ladies T-shirt",
        image: require("../../assets/ladies_shirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 7,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
    ],
  },
  {
    id: 3,
    image: require("../../assets/shoes.png"),
    title: "Shoes",
    data: [
      {
        id: 1,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 2,
        name: "Custom Name Signature T-Shirt",
        image: require("../../assets/custom_name.jpg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 3,
        name: "Unisex White T-shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "FullAddict",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 4,
        name: "V-Neck T-shirt",
        image: require("../../assets/V-neck.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 5,
        name: "Slim-Fit T-shirt",
        image: require("../../assets/slim_fit.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 6,
        name: "Ladies T-shirt",
        image: require("../../assets/ladies_shirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 7,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
    ],
  },
  {
    id: 4,
    image: require("../../assets/jacket.png"),
    title: "Jacket",
    data: [
      {
        id: 1,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 2,
        name: "Custom Name Signature T-Shirt",
        image: require("../../assets/custom_name.jpg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 3,
        name: "Unisex White T-shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "FullAddict",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 4,
        name: "V-Neck T-shirt",
        image: require("../../assets/V-neck.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 5,
        name: "Slim-Fit T-shirt",
        image: require("../../assets/slim_fit.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 6,
        name: "Ladies T-shirt",
        image: require("../../assets/ladies_shirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 7,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
    ],
  },
  {
    id: 5,
    image: require("../../assets/frok.png"),
    title: "Frok",
    data: [
      {
        id: 1,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 2,
        name: "Custom Name Signature T-Shirt",
        image: require("../../assets/custom_name.jpg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 3,
        name: "Unisex White T-shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "FullAddict",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 4,
        name: "V-Neck T-shirt",
        image: require("../../assets/V-neck.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 5,
        name: "Slim-Fit T-shirt",
        image: require("../../assets/slim_fit.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 6,
        name: "Ladies T-shirt",
        image: require("../../assets/ladies_shirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 7,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
    ],
  },
  {
    id: 6,
    image: require("../../assets/hoodie.png"),
    title: "Hoodie",
    data: [
      {
        id: 1,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 2,
        name: "Custom Name Signature T-Shirt",
        image: require("../../assets/custom_name.jpg"),
        brand: "Rare Rabit",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 3,
        name: "Unisex White T-shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "FullAddict",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 4,
        name: "V-Neck T-shirt",
        image: require("../../assets/V-neck.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 5,
        name: "Slim-Fit T-shirt",
        image: require("../../assets/slim_fit.jpeg"),
        brand: "Esquire",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 6,
        name: "Ladies T-shirt",
        image: require("../../assets/ladies_shirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
      {
        id: 7,
        name: "Logo T-Shirt",
        image: require("../../assets/logo_tshirt.jpeg"),
        brand: "Aelomart",
        discount: "-10%",
        dis_price: 3000,
        price: 2500,
        rating: 5,
        shipping: 100,
        quantity: 0,
        detail:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
      },
    ],
  },
];

export const summerItems = [
  {
    id: 1,
    image: require("../../assets/hoodie1.png"),
    title: "Hoodie",
    name: "Zip-Up Hoodie",
    company: "Nike",
    discount: "-10%",
    dis_price: 3000,
    price: 2500,
    rating: 5,
    shipping: 100,
    quantity: 0,
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
  },
  {
    id: 2,
    image: require("../../assets/pant1.png"),
    title: "Pant",
    name: "Wool Trousers",
    company: "Louis Vuitton",
    discount: "-15%",
    dis_price: 3000,
    price: 2200,
    rating: 3,
    shipping: 200,
    quantity: 0,
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
  },
  {
    id: 3,
    image: require("../../assets/shirt1.png"),
    title: "Shirt",
    name: "Cuban Collar Shirt",
    company: "Marika",
    discount: "-20%",
    dis_price: 2500,
    price: 1800,
    rating: 4,
    shipping: 200,
    quantity: 0,
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
  },
  {
    id: 4,
    image: require("../../assets/shoe1.png"),
    title: "Shoe",
    name: "Converse Shoes",
    company: "Nike",
    discount: "-10%",
    dis_price: 3500,
    price: 2800,
    rating: 5,
    shipping: 250,
    quantity: 0,
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
  },
  {
    id: 5,
    image: require("../../assets/tshirt1.png"),
    title: "T-shirt",
    name: "Half Sleeves T-shirts",
    company: "Uniqlo",
    discount: "-20%",
    dis_price: 1500,
    price: 1200,
    rating: 4,
    shipping: 0,
    quantity: 0,
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer  enim lacus. Nullam vitae sem nec purus aliquet semper non nec nisi.Curabitur purus nisl, malesuada vel mi quis, dictum ultricies arcu.",
  },
];

export const brandSlider = [
  {
    id: 1,
    image: require("../../assets/brand1.png"),
  },
  {
    id: 2,
    image: require("../../assets/brand2.png"),
  },
  {
    id: 3,
    image: require("../../assets/brand3.png"),
  },
  {
    id: 4,
    image: require("../../assets/brand4.png"),
  },
];

// export const tshirt_collection =
